### ISSUE TITLE
Laplacian Implementation Issue

### ISSUE THREAD

**Issue by MathSolverX** [Haiyun314/Image_processing#1]
### Description
The implementation of the Laplacian in the project does not seem correct.

### Expected Behavior
the discrete divergence is not compatible with <grad(f), g> = <f, -lap(g)> for all f, g

**Comment by Haiyun314** [comment]
Initially used backward propagation for both gradient and Laplacian, which was a mistake. I’ve corrected it by applying backward propagation for the gradient and the central difference for the Laplacian. The issue has been fixed, and everything works as expected now.
